### ISSUE TITLE
StatusDisplayLayout에 선택한 다이얼 시간이 제대로 표시되지 않음

### ISSUE THREAD

**Issue by CaChiJ** [ProjectFRIDAY/Plan-Dial#13]
StatusDisplayLayout에 다이얼의 남은 시간이 잘못 표시되는 버그가 있습니다.
현재 시각 이후로 시작일이 설정된 경우에 위 오류가 발생하는 것 같습니다.
다이얼의 getSeconds() 함수가 16억 정도의 값을 반환하는 것으로 보아 오버플로우의 가능성도 있어 보입니다.

![버그](https://user-images.githubusercontent.com/53603478/151993870-f64c9c0d-0d28-4869-97d5-0fe4c65ec3c9.PNG)

**Comment by Mango-Juice** [comment]
해당 이슈는 Dial 클래스의 `getLeftTimeInMillis()` 함수에서 발생한 것으로 보입니다.
현재 코드에서 시작일이 현재 시각보다 미래일 때 시작일까지 **남은 시간(시작일 - 현재 시각)이 아닌 시작일 그 자체**를 반환하는 것을 확인하였습니다.
빠르게 수정하여 커밋하도록 하겠습니다!

**Comment by Mango-Juice** [comment]
해당 내용 `master` 브랜치에 [커밋](https://github.com/ProjectFRIDAY/Plan-Dial/commit/e9c424bffc44daf6b3d0d4a1ce59462c98bf7b83)하였습니다.
또한, 원활한 테스트를 위해 `dial-create-page` 브랜치에도 해당 내용을 반영해놓았습니다.
